### ISSUE TITLE
Prevent Kiwix from Booting any "hidden" modules

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/contentshell#10]
That'd be cool...

**Comment by needlestack** [comment]
So I understand - is the idea here so that if you go to the kiwix library page - that it doesn't show anything hidden in the admin interface?

**Comment by spatiald** [comment]
@needlestack That is my understanding.

On a similar topic, I looked at your kiwix start perl script.  I had some issues using it on the CAP (dependency errors I didn't want to follow down the rabbit hole).  I ported it to bash (yeah, I know...but the end result works).  
```
#!/bin/bash
#-------------------------------------------
# This script is used to refresh the kiwix library upon restart to
# include everything in the rachel modules directory. It is used
# as part of the kiwix init.d script
#
# Author: Sam <sam@hackersforcharity.org>
# Based on perl version by Jonathan Field <jfield@worldpossible.org>
# Date: 2016-04-27
#-------------------------------------------

# Create tmp file (clean out new lines, etc)
tmp=`mktemp`
library="/media/RACHEL/kiwix/data/library/library.xml"

# Remove/recreate existing library
rm -f $library; touch $library

# Find all the zim files in the modules directoy
# then take only the first from each module
echo $(ls /media/RACHEL/rachel/modules/*/data/content/*.zim 2>/dev/null) > $tmp
for i in $(cat $tmp); do
    if [[ $? -ge 1 ]]; then echo "No zims found."; fi
    cmd="/var/kiwix/bin/kiwix-manage $library add $i"
    moddir="$(echo $i | cut -d'/' -f1-6)"
    zim="$(echo $i | cut -d'/' -f9)"
    if [[ -d "$moddir/data/index/$zim.idx" ]]; then
        cmd="$cmd --indexPath=$moddir/data/index/$zim.idx"
    fi
    $cmd
    if [[ $? -ge 1 ]]; then echo "Couldn't add $zim to library"; fi
done

# Restart Kiwix
killall /var/kiwix/bin/kiwix-serve
/var/kiwix/bin/kiwix-serve --daemon --port=81 --library $library
rm -f $tmp
```

I will add this to the CAP startup script and all should be good.  I like that all files stay in their module folders. Great work @needlestack 

Okay, that brings up the next point.  Do we have some way to identify to the scripts (my bash and @needlestack perl) that a module was hidden in the admin console?

**Comment by needlestack** [comment]
Huh, I'm surprised it gave you issues... it shouldn't have any dependencies beyond perl itself. Is there no perl on the CAP? Very cool bash work though :)

One thing: I notice that it doesn't default to a sample-library.xml like the other version. That's not critical, but without it you can't verify that kiwix is running unless there's a kiwix-based rachel module installed. I thought it was nice to have it at least show something rather than a blank page if you go to the kiwix port in the browser. Your call for the CAP!

**Comment by needlestack** [comment]
To answer your question: the info on what is hidden or not is in contentshell's admin.sqlite file - you can access it from the command line:

`sqlite3 /media/RACHEL/rachel/admin.sqlite 'select moddir from modules where hidden = 1'`

That should get you the module names that are hidden.

**Comment by spatiald** [comment]
Yeah, our Kiwix install doesn't have a sample file.  I figured I would add
that in by pulling your file and then build it into future installs.  Is
the file up on the rachel server or otherwise available.  I did like the
idea of the sample file.

Sweet on the sqlite db...I'll update the script to check/remove those
modules that are selected as hidden.

**Comment by needlestack** [comment]
Ok, this ended up being a change to rachelpiOS, but it is all set in the current version.

@spatiald - one gotcha I ran into when the database doesn't exist yet (on initial startup) it's easy enough to ignore errors, but I found that just running `sqlite3 admin.sqlite` created the file, and with the wrong permisions! So you have to check if it exists first, and don't try looking in it if it isn't there :)

You can peek at my new version of [rachel-kiwix-start.pl](https://github.com/rachelproject/rachelpiOS/blob/master/files/rachel-kiwix-start.pl) in rachelpiOS.
