### ISSUE TITLE
Possible to have two index.htmlf files

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/contentshell#3]
Is it possible to have two different formats of index.htmlf?  For instance, on RACHEL-Pi and WAMP where there is no "teacher section" the index.php page uses index.htmlf files to populate.  But for the new CAP where we have a teacher login that index.php page could use index.htmlg or something.  That way, we don't have to have two different content packs for the different devices, just a different index.php page.

This evolved from trying to include teacher's editions of textbooks in a password protected section of the CAP.  It's also relevant for different ports in KA-Lite we want to forward to from the index.php page based on device.

**Comment by needlestack** [comment]
@spatiald - what's the best way to determine that we're running on the CAP? I can add a PHP flag so that the rachel-index.php file can selectively show this type of content.

But is it really a CAP thing? Or is that just one of the possible reasons to show this content? Should it just be a flag called $show_teacher and that gets populated by either a) being on a CAP or b) some other sets of circumstances?

Just trying to avoid duplicating the whole rachel-index.php if we don't have to...

**Comment by spatiald** [comment]
@j-schwartz Can you explain the purpose in another way?  i don't think I follow the reasoning behind this.  Here is what I visualize you are saying:  the teacher section on the CAP is accessed via port 8090 and using the teacher login.  On the Pi, you don't have that luxury, so you password-protect the page using apache...is that correct?   

@needlestack Currently, to identify a CAP, you could check for the directory /media/RACHEL/rachel (that is our web directory).  I would like to add a file to both Pis and CAPs that we mod with RACHEL to allow us to more easily verify versions, etc.  I discussed this idea briefly [here](https://github.com/rachelproject/contentshell/issues/8) as I think it would be relevant to many other scripts.

**Comment by j-schwartz** [comment]
we have the new sorting tools
